### ISSUE TITLE
[Bug report]: insufficient tokens after generation

### ISSUE THREAD

**Issue by cmdillon** [ag-grid/ag-grid-figma-design-system#6]
### Your bug report...

after generating tokens only 43 tokens are generated. I would think that 119 should be the result as the all-props.json file has this amount of tokens.

**Comment by markdurrant** [comment]
Hi @cmdillon. Thanks once again for your feedback!

The Figma design system does not yet every CSS variable that we support in our themes. Currently `all-props.json` is used to make sure we don't output any extra tokens we need in the Figma but do not have CSS variable equivalents. 

However I have just [merged a PR](https://github.com/ag-grid/ag-grid-figma-design-system/pull/5) that increases the number of tokens by more than 50%. We now output 70+ CSS variables per theme. 

If there is a token/variable that is missing from the export that's required for your work please let us know and we'll add support for it to our roadmap. 

I'm closing this issue for now, but I'll re-open if you find other issues with insufficient tokens.

**Comment by cmdillon** [comment]
thx! i'll give it a try.
